import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { getRecallText, getRecallQuestions, type RecallContent } from '@/services/recallService';
import { saveRecallTest } from '@/services/storage';
import type { CaptureInterruptionReason } from '@/services/captureValidity';
import type { CaptureFinishedInfo } from './useCaptureLifecycle';
import type { PreTestContext, RecallQuestion, RecallTestResult } from '@/types';

// Recall flow extracted from EyeTrackingTestScreen: owns the capture/recall mode,
// the AI-generated recall passage, the post-capture quiz generation, the quiz
// outcome and its persistence (saveRecallTest). The screen keeps everything the
// flow merely drives: the displayed reading text (setText/readingTextState) is
// reached only through onReadingTextChange, the short capture-mode passage is
// generated by the screen (generic reading content, not recall) and handed in via
// registerShortText, and the capture linkage arrives through noteCaptureFinished
// called from the screen's onCaptureFinished. The hook knows nothing about the
// camera, canvas, capture internals (beyond the finish info) or UI.

export type RecallTestMode = 'capture' | 'recall';
export type ReadingTextState = 'loading' | 'ready' | 'error';
export type RecallGenState = 'idle' | 'generating' | 'error';

export interface RecallOutcome {
  score: number;
  total: number;
  topic: string;
}

// Link between the quiz result and the validation capture recorded while reading.
export interface RecallCaptureLink {
  captureId: string;
  readingDurationMs: number;
}

// --- Pure decisions (unit-tested) ---

// Mode switch guard: a running capture pins the mode (swapping the passage would
// re-wrap the stimulus mid-measurement), and re-selecting the current mode is a no-op.
export function canSwitchRecallMode(
  next: RecallTestMode,
  current: RecallTestMode,
  capturing: boolean,
): boolean {
  return next !== current && !capturing;
}

// The quiz only fires over a clean (uninterrupted) capture, in recall mode, with the
// recall passage actually on screen. The capture itself is saved either way — only
// the quiz is at the mercy of the AI call.
export function shouldGenerateRecallQuiz(input: {
  interruption: CaptureInterruptionReason | null;
  mode: RecallTestMode;
  hasRecallContent: boolean;
}): boolean {
  return !input.interruption && input.mode === 'recall' && input.hasRecallContent;
}

export function recallCaptureLink(info: { captureId: string; durationMs: number }): RecallCaptureLink {
  return { captureId: info.captureId, readingDurationMs: Math.round(info.durationMs) };
}

export function buildRecallTestResult(input: {
  content: RecallContent;
  questions: RecallQuestion[];
  answers: number[];
  score: number;
  lastCapture: RecallCaptureLink | null;
  context: PreTestContext | null;
  now?: number;
}): RecallTestResult {
  const now = input.now ?? Date.now();
  return {
    id: now.toString(),
    timestamp: now,
    topic: input.content.topic,
    text: input.content.text,
    questions: input.questions,
    answers: input.answers,
    score: input.score,
    readingDurationMs: input.lastCapture?.readingDurationMs ?? 0,
    captureId: input.lastCapture?.captureId,
    context: input.context ?? undefined,
  };
}

export interface UseRecallFlowOptions {
  initialMode?: RecallTestMode;
  // Lazily read so callers can wire a ref that is declared after this hook
  // (same pattern as useCaptureLifecycle's getDetectionFps).
  isCapturing: () => boolean;
  // Pre-test context at quiz-save time; the screen owns the context form/refs.
  getPreTestContext: () => PreTestContext | null;
  // The screen owns the displayed reading text; the flow drives it through this
  // callback exactly where the inline code paired setText + setReadingTextState.
  onReadingTextChange: (text: string, state: ReadingTextState) => void;
}

export interface RecallFlowHandle {
  testMode: RecallTestMode;
  recallContent: RecallContent | null;
  recallQuiz: RecallQuestion[] | null;
  recallGenState: RecallGenState;
  recallOutcome: RecallOutcome | null;
  switchMode: (mode: RecallTestMode) => void;
  // Store the short capture-mode passage; restores it as the displayed text when
  // (and only when) the current mode is 'capture'.
  registerShortText: (text: string) => void;
  // Called from the screen's onCaptureFinished: records the capture link and, for a
  // clean recall capture, generates the quiz over the text that was on screen.
  noteCaptureFinished: (info: CaptureFinishedInfo) => void;
  handleQuizDone: (answers: number[], score: number) => void;
  dismissRecallError: () => void;
  clearRecallOutcome: () => void;
}

export function useRecallFlow(options: UseRecallFlowOptions): RecallFlowHandle {
  const { initialMode = 'capture' } = options;

  // 'capture' shows the short AI text and just records gaze; 'recall' swaps in an
  // intermediate factual text and, after "Terminei de ler", runs a 6-question quiz.
  const [testMode, setTestMode] = useState<RecallTestMode>(initialMode);
  const testModeRef = useRef<RecallTestMode>(initialMode);
  const [recallContent, setRecallContent] = useState<RecallContent | null>(null);
  const recallContentRef = useRef<RecallContent | null>(null);
  const shortTextRef = useRef<string | null>(null);
  const [recallQuiz, setRecallQuiz] = useState<RecallQuestion[] | null>(null);
  const [recallGenState, setRecallGenState] = useState<RecallGenState>('idle');
  const [recallOutcome, setRecallOutcome] = useState<RecallOutcome | null>(null);
  const lastRecallCaptureRef = useRef<RecallCaptureLink | null>(null);

  // Latest committed callbacks: async continuations and capture-finish reactions
  // read these refs instead of a render-frozen closure.
  const isCapturingRef = useRef(options.isCapturing);
  const getPreTestContextRef = useRef(options.getPreTestContext);
  const onReadingTextChangeRef = useRef(options.onReadingTextChange);
  useLayoutEffect(() => {
    isCapturingRef.current = options.isCapturing;
    getPreTestContextRef.current = options.getPreTestContext;
    onReadingTextChangeRef.current = options.onReadingTextChange;
  });

  const loadRecallText = () => {
    onReadingTextChangeRef.current('Gerando texto de leitura para recall…', 'loading');
    setRecallContent(null);
    recallContentRef.current = null;
    getRecallText()
      .then(content => {
        setRecallContent(content);
        recallContentRef.current = content;
        onReadingTextChangeRef.current(content.text, 'ready');
      })
      .catch(() => {
        onReadingTextChangeRef.current('Não foi possível gerar o texto de recall por IA.', 'error');
      });
  };

  const switchMode = (mode: RecallTestMode) => {
    if (!canSwitchRecallMode(mode, testMode, isCapturingRef.current())) return;
    setTestMode(mode);
    testModeRef.current = mode;
    setRecallOutcome(null);
    if (mode === 'recall') {
      loadRecallText();
    } else if (shortTextRef.current) {
      onReadingTextChangeRef.current(shortTextRef.current, 'ready');
    }
  };

  useEffect(() => {
    if (initialMode === 'recall') {
      switchMode('recall');
    }
  // switchMode is intentionally not a dependency; this sync is only for the initial mount mode.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialMode]);

  const registerShortText = (generated: string) => {
    shortTextRef.current = generated;
    if (testModeRef.current === 'capture') {
      onReadingTextChangeRef.current(generated, 'ready');
    }
  };

  const noteCaptureFinished = (info: CaptureFinishedInfo) => {
    // The reading just ended: keep the capture link either way, quiz only for a
    // clean recall run over a passage that was actually on screen.
    lastRecallCaptureRef.current = recallCaptureLink(info);
    const content = recallContentRef.current;
    if (!content || !shouldGenerateRecallQuiz({
      interruption: info.interruption,
      mode: testModeRef.current,
      hasRecallContent: content !== null,
    })) return;
    setRecallGenState('generating');
    getRecallQuestions(content.text)
      .then(questions => { setRecallQuiz(questions); setRecallGenState('idle'); })
      .catch(() => setRecallGenState('error'));
  };

  const handleQuizDone = (answers: number[], score: number) => {
    const content = recallContentRef.current;
    if (content && recallQuiz) {
      const result = buildRecallTestResult({
        content,
        questions: recallQuiz,
        answers,
        score,
        lastCapture: lastRecallCaptureRef.current,
        context: getPreTestContextRef.current(),
      });
      saveRecallTest(result).catch(() => {/* keep the on-screen result */});
      setRecallOutcome({ score, total: recallQuiz.length, topic: content.topic });
    }
    setRecallQuiz(null);
    // Fresh text for the next run — rereading the same passage would inflate recall.
    loadRecallText();
  };

  return {
    testMode,
    recallContent,
    recallQuiz,
    recallGenState,
    recallOutcome,
    switchMode,
    registerShortText,
    noteCaptureFinished,
    handleQuizDone,
    dismissRecallError: () => setRecallGenState('idle'),
    clearRecallOutcome: () => setRecallOutcome(null),
  };
}
